### ISSUE TITLE
Route /api/v1/users/:username 404

### ISSUE THREAD

**Issue by Phpp1010** [thm-mni-ii/submissioncheck#118]
@bees4ever Response is 404, but user exist and can't be deleted.

**Comment by bees4ever** [comment]
@Phpp1010 Oh yes we somehow decided to use the userid here, not the name, but ok I will also enable this soon

**Comment by Phpp1010** [comment]
@bees4ever You don't have to if it is working with the userid. I changed the wiki. Just update the wiki if updates where made.
