### ISSUE TITLE
Routes from username to userid

### ISSUE THREAD

**Issue by Phpp1010** [thm-mni-ii/submissioncheck#149]
@bees4ever Change route parameter that require username to userid

**Comment by bees4ever** [comment]
@Phpp1010 These routes where I must change it, are only the grant / revoke routes of a tutor docent, is that right? Should I changed this routes too, as combined request?

**Comment by Phpp1010** [comment]
@bees4ever I think there are the only one left, yes. You can let them be separate. Granting and revoking docent, tutor rights to a course are separate things.
