### ISSUE TITLE
Types of tasks

### ISSUE THREAD

**Issue by Phpp1010** [thm-mni-ii/submissioncheck#154]
@bees4ever Route that gives back all types the system currently has.

Response:
```
types: ["JAVA", "FILE", "SQL"...]
```

**Comment by bees4ever** [comment]
HI @Phpp1010 yes we should discuss this later, because there is some logic issue.

**Comment by bees4ever** [comment]
@Phpp1010 We should only use the filed "testsystem_id" if a task is created or updated to specify which type this task has, a list of all such system is available here (only for Docent, Admin):

/api/v1/testsystems

You already can get this information and use this for task PUT / POST but I have to clean up the old "test_type" field.
