### ISSUE TITLE
Angular Material

### ISSUE THREAD

**Issue by andrej-sajenko** [thm-mni-ii/submissioncheck#5]
Add angular material to the angular2 app.

**Comment by MhmdKorhani** [comment]
For npm write in your command prompt `npm install --save @angular/material @angular/cdk` to install angular material to your node modules. **P.S if you are using angular 2 be sure that you installed angular material version 5.2.4**
Then write `npm install --save hammerjs` so hammer.js can be installed in your node modules.

**In your app.module.ts:**
1. `import { BrowserAnimationsModule } from '@angular/platform-browser/animations';`
2. `import { MaterialModule } from './Modules/material/material.module';`
3. Add them into the imports in the declaration: [
BrowserAnimationsModule,
MaterialModule
]
4. Create a Custom.scss file in your src directory.
5. Add the custom.scss in your styles in angular-cli.json file. _Follow this link to see what to write in Custom.scss [Angular Material Themes](https://material.angular.io/guide/theming)_
6. For each component you want to use import them in your app.module.ts Example: _if you want to use the button add import the MatButtonModule and add it to your imports in the declaration._
7. Run `ng serve --open`

You can follow this link to get into details [Angular Material](https://material.angular.io/guide/getting-started)

**Comment by andrej-sajenko** [comment]
@MhmdKorhani Thank you very much for giving us the instructions.
