### ISSUE TITLE
after Rework WS no index.html

### ISSUE THREAD

**Issue by bees4ever** [thm-mni-ii/submissioncheck#62]
After we reworked WS, the index.html is not longer reachable.

**Comment by bees4ever** [comment]
File WebConfig.scala cuases trouble because of now MVC is activated.

**Comment by andrej-sajenko** [comment]
I will check it.

**Comment by andrej-sajenko** [comment]
resolved with 4376e3653b0aeebecae64930a6726116eadf39de
